---
title: "up1-Aizah-Khurram"
output: github_document
---

## Mojito Recipe

### Ingredients
* 6 mint leaves
* 3/4 oz simple sugar
* 3/4 oz fresh lime juice
* 1 1/2 oz white rum
* 1 1/2 oz club soda

### Special Tools
* Shaker
* Strainer
* Muddler

### Method
1. In a shaker, **lightly** muddle the mint.
2. Add the simple syrup, lime juice and rum, and fill with ice.
3. Shake well and pour (*unstrained*) into a highball glass.
4. Top with the club soda and garnish with a mint sprig.

|Criteria     | Result|
|--------     | -------|
|Base alcohol | Rum|
|Hours        | Afternoon, evening, with dinner|
|Theme        | Summer|

You can find this recipe [here](https://www.liquor.com/recipes/mojito/#gs.46XRbqo)

## Quadratic Equation

#### General Form
In algebra, a quadratic equation is any equaition having the form 

\[ax^2 + bx + c=0\]

where x represents an unknown, and a,b,c represent known numbers such that *a* is not equal to 0. 

#### Roots of the general quadratic equation
Completing the square can be used to derive a general formula for solving quadratic equations. Taking the square root of both sides and isolating *x* gives:

\[\frac [b^2 +- sqrt [b^2 -4ac]] [2ac]]

This information was taken from [Wikipedia](https://en.wikipedia.org/wiki/Quadratic_equation)

## Comments and Reflections

The tutorials listed in the assigment made understanding and applying the various elements easier even though this was my first time using markdown. The most time consuming part, for me, was trying to figure out how to write the roots of the equation, which I don't think is correct. 




